name: MacOS

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        compiler: [8, 9, clang]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: sysctl -a | grep machdep.cpu

    - name: Print OS information
      run: system_profiler SPSoftwareDataType

    - name: Install dependencies
      run: brew install libpng libjpeg libdc1394 opencv

    - name: Clone ViSP-images
      run: git clone --depth 1 https://github.com/lagadic/ViSP-images ${HOME}/ViSP-images

    - name: Set VISP_INPUT_IMAGE_PATH env
      run: echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV

    - name: Configure gcc
      if: ${{ matrix.compiler }} != 'clang'
      run: CC=/usr/bin/gcc-${{ matrix.compiler }} CXX=/usr/bin/g++-${{ matrix.compiler }}

    # Openblas location is exported explicitly because openblas is keg-only,
    # which means it was not symlinked into /usr/local/.
    - name: Configure CMake
      run: |
        export LDFLAGS="-L/usr/local/opt/openblas/lib"
        export CPPFLAGS="-I/usr/local/opt/openblas/include"
        mkdir -p build
        cd build
        cmake .. -DCMAKE_FIND_FRAMEWORK=LAST
        cat ViSP-third-party.txt
        echo ${HOME}
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests
      working-directory: build
      run: ctest --output-on-failure
