name: Ubuntu-sanitizers

on: [push, pull_request]

jobs:
  build-ubuntu-sanitizers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags: ["-fsanitize=address", "-fsanitize=leak"]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: lscpu

    - name: Print OS information
      run: lsb_release -a

    - name: Install dependencies
      run: sudo apt-get install -y libdc1394-22-dev libopencv-dev libopenblas-dev

    - name: Clone ViSP-images
      run: git clone --depth 1 https://github.com/lagadic/ViSP-images ${HOME}/ViSP-images

    - name: Set VISP_INPUT_IMAGE_PATH env
      run: echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_C_FLAGS=${{ matrix.flags }} -DCMAKE_CXX_FLAGS=${{ matrix.flags }} -DCMAKE_LDFLAGS=${{ matrix.flags }} -DCMAKE_BUILD_TYPE=Debug
        cat ViSP-third-party.txt
        echo ${HOME}
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests
      working-directory: build
      run: ctest --output-on-failure
