name: Ubuntu

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        compiler: [8, 9]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: lscpu

    - name: Print OS information
      run: lsb_release -a

    - name: Install dependencies
      run: sudo apt-get install -y libdc1394-22-dev libopencv-dev libopenblas-dev

    - name: Clone ViSP-images
      run: git clone --depth 1 https://github.com/lagadic/ViSP-images ${HOME}/ViSP-images

    - name: Set VISP_INPUT_IMAGE_PATH env
      run: echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        CC=/usr/bin/gcc-${{ matrix.compiler }}
        CXX=/usr/bin/g++-${{ matrix.compiler }}
        echo "CC: $CC"
        echo "CXX: $CXX"
        cmake .. -DCMAKE_C_COMPILER="${CC}" -DCMAKE_CXX_COMPILER="${CXX}"
        cat ViSP-third-party.txt
        echo ${HOME}
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Run unit tests
      working-directory: build
      run: ctest --output-on-failure
